version: '3.4'

services:
  elk_stack:
    build: .
    image: elk_stack
    container_name: elk
    hostname: elkhost
    ports:
      - 9200:9200
      - 9300:9300
      - 5601:5601
      - 9001:9001
    networks:
      - elknet  

networks:
  elknet:
    driver: bridge      